"""Company and keyword lists.

Add or remove target employers in COMPANIES.
Add or remove role search terms in ROLE_KEYWORDS.
"""

COMPANIES = [
    "Google Ireland Limited",
    "Microsoft Ireland Research Unlimited Company",
    "Microsoft Ireland Operations Limited",
    "Amazon Web Services EMEA SARL",
    "Amazon Development Centre Ireland Limited",
    "Amazon Data Services Ireland Limited",
    "Amazon Ireland Support Services Limited",
    "Stripe Technology Company Limited",
    "Meta Platforms Ireland Limited",
    "TikTok Technology Limited",
    "Apple Distribution International Limited",
    "Apple Operations International Limited",
    "LinkedIn Ireland Unlimited Company",
    "Adobe Systems Software Ireland Limited",
    "ServiceNow Ireland Limited",
    "Workday Limited",
    "MongoDB Limited",
    "HubSpot Ireland Limited",
    "Intercom R&D Unlimited Company",
    "Toasttab Ireland Limited",
    "Datadog Ireland Limited",
    "Zendesk International Limited",
    "Guidewire Software Ireland Limited",
    "OpenAI Ireland Limited",
    "Squarespace Ireland Limited",
    "2K Games Dublin Limited",
    "Accenture Limited",
    "Accenture Global Solutions Limited",
    "Tata Consultancy Services Limited",
    "Tata Consultancy Services Ireland Limited",
    "Cognizant Technology Solutions Ireland Limited",
    "Infosys Limited",
    "Infosys BPM Limited",
    "HCL Ireland Information Systems Limited",
    "HCL Technologies Limited",
    "Capgemini Ireland Limited",
    "Deloitte Ireland LLP",
    "Ernst & Young",
    "KPMG",
    "PricewaterhouseCoopers Services",
    "IBM Global Services Limited",
    "IBM Ireland Limited",
    "NTT DATA Services Ireland Limited",
    "Version 1 Software Limited",
    "GlobalLogic Software and Technology Ireland Limited",
    "Liberty Information Technology Limited",
    "General Motors IT Services Ireland Ltd",
    "Red Hat Limited",
    "MasterCard Ireland Limited",
    "Fiserv Solutions Europe Limited",
    "PayPal Europe Services Limited",
    "Circle Internet Financial Trading Company Limited",
    "Fenergo Limited",
    "J.P. Morgan SE",
    "Bank of America Europe Designated Activity Company",
    "Citibank Europe Public Limited Company",
    "Citibank N.A.",
    "BNY Mellon Fund Services Ireland DAC",
    "Bank of Ireland Group PLC",
    "Allied Irish Banks PLC",
    "Permanent TSB Public Limited Company",
    "State Street Technology Ireland Ltd",
    "ICE Data Services Ireland Limited",
    "Bloomberg Data Management Services Limited",
    "Intel Ireland Limited",
    "Intel Research and Development Ireland Limited",
    "Analog Devices International Unlimited Company",
    "Dell Products Unlimited Company",
    "EMC Information Systems International Unlimited Company",
    "Cisco Systems Internetworking Ireland Limited",
    "Cadence Design Systems Ireland Limited",
    "Arista Technology Ireland Unlimited Company",
    "Huawei Technologies Ireland Co Ltd",
    "Infineon Technologies Semiconductor Ireland Limited",
    "Applied Software Consultants Limited",
    "Kaseya Limited",
    "Cloudera International Limited",
    "Logitech Ireland Services Limited",
    "McKesson Cork Business Solutions Unlimited Company",
    "Optum Services Ireland Limited",
    "SAP Ireland Limited",
    "Oracle EMEA Ltd",
    "Oracle Financial Services Software B.V",
    "Eli Lilly Kinsale Limited",
    "Eli Lilly Cork Limited",
    "WuXi Biologics Ireland Limited",
    "Pfizer Ireland Pharmaceuticals Unlimited Company",
    "MSD International GmbH",
    "Johnson & Johnson Vision Care Ireland Unlimited Company",
    "Boston Scientific Ireland Limited",
    "Boston Scientific Cork",
    "Abbott Ireland",
    "Abbott Diagnostics",
    "Regeneron Ireland DAC",
    "Medtronic Vascular Galway Unlimited Company",
    "Stryker Ireland Limited",
    "Alexion Pharma International Operations Limited",
    "Gilead Sciences Ireland UC",
]

ROLE_KEYWORDS = [
    "QA Automation Engineer",
    "SDET",
    "Software Test Engineer",
    "Test Automation Engineer",
    "API Test Engineer",
    "Performance Test Engineer",
    "QA Engineer",
    "Automation Tester",
    "Software Engineer in Test",
    "Production Support QA",
    "FinTech QA",
    "Cypress",
    "Playwright",
    "Selenium",
    "Postman",
    "Rest Assured",
    "JMeter",
    "CI/CD QA",
    "Test Engineer",
    "Quality Engineer",
    "Validation Engineer",
    "CSV Tester",
]
