from __future__ import annotations

from models import CompanyConfig, SourceConfig


def source(source_type: str, **kwargs: str) -> SourceConfig:
    return SourceConfig(source_type=source_type, **kwargs)


def company(
    legal_name: str,
    brand_name: str,
    aliases: list[str],
    careers_url: str = "",
    sources: list[SourceConfig] | None = None,
    priority: bool = False,
) -> CompanyConfig:
    return CompanyConfig(legal_name, brand_name, aliases, careers_url, sources or [], priority)


PRIORITY_BRANDS = {
    "Cubic Telecom",
    "Stripe",
    "Workday",
    "Amazon",
    "Mastercard",
    "Version 1",
    "Accenture",
    "Fiserv",
    "PayPal",
    "Guidewire",
    "AbbVie",
}


COMPANIES = [
    company("Cubic Telecom Limited", "Cubic Telecom", ["Cubic Telecom", "Cubic³", "Cubic"], "https://www.cubic3.com/careers", [source("ashby", slug="cubic3")], True),
    company("Google Ireland Limited", "Google", ["Google"], "https://www.google.com/about/careers/applications/jobs/results/", [source("company_careers", endpoint="https://www.google.com/about/careers/applications/jobs/results/")]),
    company("Microsoft Ireland Research Unlimited Company", "Microsoft", ["Microsoft"], "https://jobs.careers.microsoft.com/global/en/search", [source("company_careers", endpoint="https://jobs.careers.microsoft.com/global/en/search")]),
    company("Microsoft Ireland Operations Limited", "Microsoft", ["Microsoft"], "https://jobs.careers.microsoft.com/global/en/search", [source("company_careers", endpoint="https://jobs.careers.microsoft.com/global/en/search")]),
    company("Amazon Web Services EMEA SARL", "Amazon", ["Amazon", "AWS"], "https://www.amazon.jobs", [source("amazon_jobs")], True),
    company("Amazon Development Centre Ireland Limited", "Amazon", ["Amazon", "AWS"], "https://www.amazon.jobs", [source("amazon_jobs")]),
    company("Amazon Data Services Ireland Limited", "Amazon", ["Amazon", "AWS"], "https://www.amazon.jobs", [source("amazon_jobs")]),
    company("Amazon Ireland Support Services Limited", "Amazon", ["Amazon", "AWS"], "https://www.amazon.jobs", [source("amazon_jobs")]),
    company("Stripe Technology Company Limited", "Stripe", ["Stripe"], "https://stripe.com/jobs", [source("greenhouse", slug="stripe")], True),
    company("Meta Platforms Ireland Limited", "Meta", ["Meta"], "https://www.metacareers.com/jobs", [source("company_careers", endpoint="https://www.metacareers.com/jobs")]),
    company("TikTok Technology Limited", "TikTok", ["TikTok"], "https://careers.tiktok.com", [source("company_careers", endpoint="https://careers.tiktok.com/search")]),
    company("Apple Distribution International Limited", "Apple", ["Apple"], "https://jobs.apple.com", [source("company_careers", endpoint="https://jobs.apple.com/en-ie/search")]),
    company("Apple Operations International Limited", "Apple", ["Apple"], "https://jobs.apple.com", [source("company_careers", endpoint="https://jobs.apple.com/en-ie/search")]),
    company("LinkedIn Ireland Unlimited Company", "LinkedIn", ["LinkedIn"], "https://www.linkedin.com/careers", [source("company_careers", endpoint="https://www.linkedin.com/careers/jobs")]),
    company("Adobe Systems Software Ireland Limited", "Adobe", ["Adobe"], "https://careers.adobe.com/us/en/search-results", [source("phenom", endpoint="https://careers.adobe.com/widgets")]),
    company("ServiceNow Ireland Limited", "ServiceNow", ["ServiceNow"], "https://careers.servicenow.com", [source("company_careers", endpoint="https://careers.servicenow.com/jobs")]),
    company("Workday Limited", "Workday", ["Workday"], "https://workday.wd5.myworkdayjobs.com/Workday", [source("workday", host="workday.wd5.myworkdayjobs.com", tenant="workday", site="Workday")], True),
    company("MongoDB Limited", "MongoDB", ["MongoDB"], "https://www.mongodb.com/careers", [source("lever", slug="mongodb")]),
    company("HubSpot Ireland Limited", "HubSpot", ["HubSpot"], "https://www.hubspot.com/careers/jobs", [source("greenhouse", slug="hubspotjobs")]),
    company("Intercom R&D Unlimited Company", "Intercom", ["Intercom"], "https://www.intercom.com/careers", [source("greenhouse", slug="intercom")]),
    company("Toasttab Ireland Limited", "Toast", ["Toast"], "https://careers.toasttab.com", [source("greenhouse", slug="toast")]),
    company("Datadog Ireland Limited", "Datadog", ["Datadog"], "https://careers.datadoghq.com", [source("greenhouse", slug="datadog")]),
    company("Zendesk International Limited", "Zendesk", ["Zendesk"], "https://jobs.zendesk.com", [source("company_careers", endpoint="https://jobs.zendesk.com")]),
    company("Guidewire Software Ireland Limited", "Guidewire", ["Guidewire"], "https://careers.guidewire.com", [source("workday", host="wd5.myworkdaysite.com", tenant="guidewire", site="external")], True),
    company("OpenAI Ireland Limited", "OpenAI", ["OpenAI"], "https://openai.com/careers", [source("ashby", slug="openai")]),
    company("Squarespace Ireland Limited", "Squarespace", ["Squarespace"], "https://www.squarespace.com/about/careers", [source("greenhouse", slug="squarespace")]),
    company("2K Games Dublin Limited", "2K Games", ["2K Games", "2K"], "https://2k.com/jobs", [source("greenhouse", slug="2k")]),
    company("Accenture Limited", "Accenture", ["Accenture"], "https://www.accenture.com/ie-en/careers/jobsearch", [source("workday", host="accenture.wd103.myworkdayjobs.com", tenant="accenture", site="AccentureCareers")], True),
    company("Accenture Global Solutions Limited", "Accenture", ["Accenture"], "https://www.accenture.com/ie-en/careers/jobsearch", [source("workday", host="accenture.wd103.myworkdayjobs.com", tenant="accenture", site="AccentureCareers")]),
    company("Tata Consultancy Services Limited", "TCS", ["Tata Consultancy Services", "TCS"], "https://www.tcs.com/careers", [source("company_careers", endpoint="https://www.tcs.com/careers")]),
    company("Tata Consultancy Services Ireland Limited", "TCS", ["Tata Consultancy Services", "TCS"], "https://www.tcs.com/careers", [source("company_careers", endpoint="https://www.tcs.com/careers")]),
    company("Cognizant Technology Solutions Ireland Limited", "Cognizant", ["Cognizant"], "https://careers.cognizant.com", [source("company_careers", endpoint="https://careers.cognizant.com/global-en/jobs")]),
    company("Infosys Limited", "Infosys", ["Infosys"], "https://www.infosys.com/careers", [source("company_careers", endpoint="https://www.infosys.com/careers")]),
    company("Infosys BPM Limited", "Infosys", ["Infosys BPM", "Infosys"], "https://www.infosysbpm.com/careers", [source("company_careers", endpoint="https://www.infosysbpm.com/careers")]),
    company("HCL Ireland Information Systems Limited", "HCLTech", ["HCLTech", "HCL"], "https://careers.hcltech.com/search/", [source("successfactors", endpoint="https://careers.hcltech.com/search/")]),
    company("HCL Technologies Limited", "HCLTech", ["HCLTech", "HCL"], "https://careers.hcltech.com/search/", [source("successfactors", endpoint="https://careers.hcltech.com/search/")]),
    company("Capgemini Ireland Limited", "Capgemini", ["Capgemini"], "https://www.capgemini.com/careers", [source("company_careers", endpoint="https://www.capgemini.com/careers")]),
    company("Deloitte Ireland LLP", "Deloitte", ["Deloitte"], "https://apply.deloitte.com/careers", [source("company_careers", endpoint="https://apply.deloitte.com/careers")]),
    company("Ernst & Young", "EY", ["EY", "Ernst & Young"], "https://careers.ey.com/search/", [source("successfactors", endpoint="https://careers.ey.com/search/")]),
    company("KPMG", "KPMG", ["KPMG"], "https://kpmg.com/ie/en/home/careers.html", [source("company_careers", endpoint="https://kpmg.com/ie/en/home/careers.html")]),
    company("PricewaterhouseCoopers Services", "PwC", ["PwC", "PricewaterhouseCoopers"], "https://www.pwc.ie/careers.html", [source("company_careers", endpoint="https://www.pwc.ie/careers.html")]),
    company("IBM Global Services Limited", "IBM", ["IBM"], "https://www.ibm.com/careers", [source("company_careers", endpoint="https://www.ibm.com/careers/search")]),
    company("IBM Ireland Limited", "IBM", ["IBM"], "https://www.ibm.com/careers", [source("company_careers", endpoint="https://www.ibm.com/careers/search")]),
    company("NTT DATA Services Ireland Limited", "NTT DATA", ["NTT DATA"], "https://www.nttdata.com/global/en/careers", [source("company_careers", endpoint="https://www.nttdata.com/global/en/careers")]),
    company("Version 1 Software Limited", "Version 1", ["Version 1"], "https://www.version1.com/careers", [source("smartrecruiters", slug="Version1")], True),
    company("Expleo Technology Ireland Limited", "Expleo", ["Expleo"], "https://expleo.com/global/en/careers", [source("company_careers", endpoint="https://expleo.com/global/en/careers")]),
    company("GlobalLogic Software and Technology Ireland Limited", "GlobalLogic", ["GlobalLogic"], "https://www.globallogic.com/careers", [source("company_careers", endpoint="https://www.globallogic.com/careers")]),
    company("Liberty Information Technology Limited", "Liberty IT", ["Liberty IT"], "https://www.liberty-it.co.uk/careers", [source("company_careers", endpoint="https://www.liberty-it.co.uk/careers")]),
    company("General Motors IT Services Ireland Ltd", "General Motors", ["General Motors", "GM"], "https://search-careers.gm.com", [source("company_careers", endpoint="https://search-careers.gm.com")]),
    company("Red Hat Limited", "Red Hat", ["Red Hat"], "https://www.redhat.com/en/jobs", [source("workday", host="redhat.wd5.myworkdayjobs.com", tenant="redhat", site="jobs")]),
    company("MasterCard Ireland Limited", "Mastercard", ["Mastercard"], "https://mastercard.wd1.myworkdayjobs.com/mastercard", [source("workday", host="mastercard.wd1.myworkdayjobs.com", tenant="mastercard", site="mastercard")], True),
    company("Fiserv Solutions Europe Limited", "Fiserv", ["Fiserv"], "https://careers.fiserv.com/us/en/search-results", [source("phenom", endpoint="https://careers.fiserv.com/widgets")], True),
    company("PayPal Europe Services Limited", "PayPal", ["PayPal"], "https://paypal.eightfold.ai/careers", [source("eightfold", endpoint="https://paypal.eightfold.ai/careers")], True),
    company("Circle Internet Financial Trading Company Limited", "Circle", ["Circle"], "https://careers.circle.com/us/en/search-results", [source("phenom", endpoint="https://careers.circle.com/widgets")]),
    company("Fenergo Limited", "Fenergo", ["Fenergo"], "https://www.fenergo.com/careers", [source("company_careers", endpoint="https://www.fenergo.com/careers")]),
    company("J.P. Morgan SE", "JPMorgan Chase", ["JPMorgan Chase", "J.P. Morgan"], "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001", [source("oracle_hcm", host="jpmc.fa.oraclecloud.com", site="CX_1001")]),
    company("Bank of America Europe Designated Activity Company", "Bank of America", ["Bank of America"], "https://careers.bankofamerica.com", [source("company_careers", endpoint="https://careers.bankofamerica.com")]),
    company("Citibank Europe Public Limited Company", "Citi", ["Citi", "Citibank"], "https://jobs.citi.com", [source("eightfold", endpoint="https://jobs.citi.com")]),
    company("Citibank N.A.", "Citi", ["Citi", "Citibank"], "https://jobs.citi.com", [source("eightfold", endpoint="https://jobs.citi.com")]),
    company("BNY Mellon Fund Services Ireland DAC", "BNY", ["BNY", "BNY Mellon"], "https://bnymellon.eightfold.ai/careers", [source("eightfold", endpoint="https://bnymellon.eightfold.ai/careers")]),
    company("Bank of Ireland Group PLC", "Bank of Ireland", ["Bank of Ireland"], "https://careers.bankofireland.com", [source("company_careers", endpoint="https://careers.bankofireland.com")]),
    company("Allied Irish Banks PLC", "AIB", ["AIB"], "https://jobs.aib.ie/search/", [source("successfactors", endpoint="https://jobs.aib.ie/search/")]),
    company("Permanent TSB Public Limited Company", "Permanent TSB", ["Permanent TSB"], "https://www.ptsb.ie/careers", [source("company_careers", endpoint="https://www.ptsb.ie/careers")]),
    company("State Street Technology Ireland Ltd", "State Street", ["State Street"], "https://statestreet.wd1.myworkdayjobs.com/Global", [source("workday", host="statestreet.wd1.myworkdayjobs.com", tenant="statestreet", site="Global")]),
    company("ICE Data Services Ireland Limited", "ICE", ["ICE Data Services", "ICE"], "https://www.ice.com/careers", [source("company_careers", endpoint="https://www.ice.com/careers")]),
    company("Bloomberg Data Management Services Limited", "Bloomberg", ["Bloomberg"], "https://www.bloomberg.com/company/careers", [source("company_careers", endpoint="https://www.bloomberg.com/company/careers")]),
    company("Intel Ireland Limited", "Intel", ["Intel"], "https://jobs.intel.com", [source("company_careers", endpoint="https://jobs.intel.com")]),
    company("Intel Research and Development Ireland Limited", "Intel", ["Intel"], "https://jobs.intel.com", [source("company_careers", endpoint="https://jobs.intel.com")]),
    company("Analog Devices International Unlimited Company", "Analog Devices", ["Analog Devices", "ADI"], "https://analogdevices.wd1.myworkdayjobs.com/External", [source("workday", host="analogdevices.wd1.myworkdayjobs.com", tenant="analogdevices", site="External")]),
    company("Dell Products Unlimited Company", "Dell", ["Dell"], "https://jobs.dell.com", [source("company_careers", endpoint="https://jobs.dell.com")]),
    company("EMC Information Systems International Unlimited Company", "Dell", ["Dell EMC", "Dell"], "https://jobs.dell.com", [source("company_careers", endpoint="https://jobs.dell.com")]),
    company("Cisco Systems Internetworking Ireland Limited", "Cisco", ["Cisco"], "https://careers.cisco.com/global/en/search-results", [source("phenom", endpoint="https://careers.cisco.com/widgets")]),
    company("Cadence Design Systems Ireland Limited", "Cadence", ["Cadence"], "https://cadence.wd1.myworkdayjobs.com/External_Careers", [source("workday", host="cadence.wd1.myworkdayjobs.com", tenant="cadence", site="External_Careers")]),
    company("Arista Technology Ireland Unlimited Company", "Arista", ["Arista"], "https://www.arista.com/en/careers", [source("company_careers", endpoint="https://www.arista.com/en/careers")]),
    company("Huawei Technologies Ireland Co Ltd", "Huawei", ["Huawei"], "https://career.huawei.com", [source("company_careers", endpoint="https://career.huawei.com")]),
    company("Infineon Technologies Semiconductor Ireland Limited", "Infineon", ["Infineon"], "https://www.infineon.com/careers", [source("company_careers", endpoint="https://www.infineon.com/careers")]),
    company("Applied Software Consultants Limited", "Applied Software Consultants", ["Applied Software Consultants"], "", [source("fallback_search")]),
    company("Kaseya Limited", "Kaseya", ["Kaseya"], "https://www.kaseya.com/careers", [source("greenhouse", slug="kaseya")]),
    company("Cloudera International Limited", "Cloudera", ["Cloudera"], "https://www.cloudera.com/careers", [source("workday", host="cloudera.wd5.myworkdayjobs.com", tenant="cloudera", site="External_Career")]),
    company("Logitech Ireland Services Limited", "Logitech", ["Logitech"], "https://jobs.jobvite.com/logitech", [source("company_careers", endpoint="https://jobs.jobvite.com/logitech")]),
    company("McKesson Cork Business Solutions Unlimited Company", "McKesson", ["McKesson"], "https://careers.mckesson.com", [source("company_careers", endpoint="https://careers.mckesson.com")]),
    company("Optum Services Ireland Limited", "Optum", ["Optum"], "https://careers.unitedhealthgroup.com", [source("company_careers", endpoint="https://careers.unitedhealthgroup.com")]),
    company("SAP Ireland Limited", "SAP", ["SAP"], "https://jobs.sap.com/search/", [source("successfactors", endpoint="https://jobs.sap.com/search/")]),
    company("Oracle EMEA Ltd", "Oracle", ["Oracle"], "https://eeho.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/jobsearch", [source("oracle_hcm", host="eeho.fa.us2.oraclecloud.com", site="CX_45001")]),
    company("Oracle Financial Services Software B.V", "Oracle Financial Services", ["Oracle Financial Services", "Oracle"], "https://eeho.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/jobsearch", [source("oracle_hcm", host="eeho.fa.us2.oraclecloud.com", site="CX_45001")]),
    company("Eli Lilly Kinsale Limited", "Eli Lilly", ["Eli Lilly", "Lilly"], "https://careers.lilly.com/us/en/search-results", [source("phenom", endpoint="https://careers.lilly.com/widgets")]),
    company("Eli Lilly Cork Limited", "Eli Lilly", ["Eli Lilly", "Lilly"], "https://careers.lilly.com/us/en/search-results", [source("phenom", endpoint="https://careers.lilly.com/widgets")]),
    company("WuXi Biologics Ireland Limited", "WuXi Biologics", ["WuXi Biologics"], "https://www.wuxibiologics.com/careers", [source("company_careers", endpoint="https://www.wuxibiologics.com/careers")]),
    company("Pfizer Ireland Pharmaceuticals Unlimited Company", "Pfizer", ["Pfizer"], "https://www.pfizer.com/about/careers", [source("workday", host="pfizer.wd1.myworkdayjobs.com", tenant="pfizer", site="PfizerCareers")]),
    company("MSD International GmbH", "MSD", ["MSD", "Merck"], "https://jobs.msd.com/gb/en/search-results", [source("phenom", endpoint="https://jobs.msd.com/widgets")]),
    company("Johnson & Johnson Vision Care Ireland Unlimited Company", "Johnson & Johnson", ["Johnson & Johnson", "J&J"], "https://www.careers.jnj.com", [source("company_careers", endpoint="https://www.careers.jnj.com")]),
    company("Boston Scientific Ireland Limited", "Boston Scientific", ["Boston Scientific"], "https://jobs.bostonscientific.com/search/", [source("successfactors", endpoint="https://jobs.bostonscientific.com/search/")]),
    company("Boston Scientific Cork", "Boston Scientific", ["Boston Scientific"], "https://jobs.bostonscientific.com/search/", [source("successfactors", endpoint="https://jobs.bostonscientific.com/search/")]),
    company("AbbVie Ireland NL B.V.", "AbbVie", ["AbbVie", "Allergan"], "https://careers.abbvie.com/en/jobs", [source("attrax", endpoint="https://careers.abbvie.com/en/jobs")], True),
    company("Abbott Ireland", "Abbott", ["Abbott"], "https://www.jobs.abbott", [source("workday", host="abbott.wd5.myworkdayjobs.com", tenant="abbott", site="abbottcareers")]),
    company("Abbott Diagnostics", "Abbott", ["Abbott"], "https://www.jobs.abbott", [source("workday", host="abbott.wd5.myworkdayjobs.com", tenant="abbott", site="abbottcareers")]),
    company("Regeneron Ireland DAC", "Regeneron", ["Regeneron"], "https://careers.regeneron.com", [source("company_careers", endpoint="https://careers.regeneron.com")]),
    company("Medtronic Vascular Galway Unlimited Company", "Medtronic", ["Medtronic"], "https://medtronic.eightfold.ai/careers", [source("eightfold", endpoint="https://medtronic.eightfold.ai/careers")]),
    company("Stryker Ireland Limited", "Stryker", ["Stryker"], "https://careers.stryker.com", [source("workday", host="stryker.wd1.myworkdayjobs.com", tenant="stryker", site="StrykerCareers")]),
    company("Alexion Pharma International Operations Limited", "Alexion", ["Alexion", "AstraZeneca"], "https://careers.astrazeneca.com", [source("eightfold", endpoint="https://careers.astrazeneca.com")]),
    company("Gilead Sciences Ireland UC", "Gilead", ["Gilead"], "https://www.gilead.com/careers", [source("workday", host="gilead.wd1.myworkdayjobs.com", tenant="gilead", site="gileadcareers")]),
]


TEST_MODE_COMPANIES = [company for company in COMPANIES if company.priority and company.brand_name in PRIORITY_BRANDS]
